added authentication filter and find by login methods
Martynice/Internet-shop pull request #6
Opened 2020-09-14 20:02 UTC by Martynice

2020-09-14 21:24 UTC, DariaPikul requested changes

2020-09-14 21:24 UTC, DariaPikul commented on src/main/java/com/internet/shop/web/filter/AuthenticationFilter.java
> +    }
```suggestion
    public void init(FilterConfig filterConfig) throws ServletException {
    }
```

2020-09-14 21:24 UTC, DariaPikul commented on src/main/java/com/internet/shop/web/filter/AuthenticationFilter.java
> +    }
```suggestion
    public void destroy() {
    }
```

2020-09-15 09:23 UTC, KseniiaMakarova approved these changes

2020-09-15 09:23 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/user/LoginController.java
> +            session.setAttribute("user_id", user.getId());
let's make `user_id` a constant

2020-09-15 09:23 UTC, KseniiaMakarova requested changes
fix travis please

2020-09-15 09:34 UTC, Martynice commented on src/main/java/com/internet/shop/controllers/user/LoginController.java
> +            session.setAttribute("user_id", user.getId());
done

2020-09-15 10:33 UTC, KseniiaMakarova approved these changes

2020-09-15 11:23 UTC, merged